controller_manager:
  ros__parameters:
    update_rate: 100 # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    position_controller:
      type: position_controllers/JointGroupPositionController

position_controller:
  ros__parameters:
    joints:
      - j0
      - j1
      - j2
      - j3
    command_interfaces:
      - position
    state_publish_rate: 100.0       # Hz for state publication rate
    action_monitor_rate: 20.0       # Hz for action monitoring
    allow_partial_joints_goal: true # Allows sending position goals for a subset of joints
    open_loop_control: false        # Set true if you want open-loop control
    allow_integration_in_goal_trajectories: true